### ISSUE TITLE
USER instruction for building secure Docker images

### ISSUE THREAD

**Issue by joelchen** [abiosoft/caddy-docker#11]
Should there be a USER instruction included in the Dockerfile for added security as described in https://www.youtube.com/watch?v=LmUw2H6JgJo?

**Comment by MatthewVance** [comment]
I think that's a good idea. I recently created by own Caddy Dockerfile with Debian as the base (personal preference), but used this version by @abiosoft as a template because I liked how it was constructed but one thing I added was the USER instruction. 

The Dockerfile will also need to add a Caddy user and group and run `setcap cap_net_bind_service=+ep /usr/bin/caddy` to allow lower number ports to be bound by the Caddy process without root privileges. Feel free to re-use what you can from my [Dockerfile](https://github.com/MatthewVance/caddy-docker/blob/master/Dockerfile) if you want to implement this. Alpine uses a slightly different version of `adduser` and `addgroup` so copying the command verbatim won't work. The [nginx alpine](https://github.com/nginxinc/docker-nginx/blob/11fc019b2be3ad51ba5d097b1857a099c4056213/mainline/alpine/Dockerfile) version is a good reference point for adding such a user.

**Comment by abiosoft** [comment]
Thanks for bringing attention to this @joelchen and thanks for the instructions @MatthewVance. This should make it in soon.

**Comment by abiosoft** [comment]
FYI, since current `:latest` and `:0.9.3`, no more unprivileged `caddy` user and there should be no write permission issues anymore. I had to revert this update as I've had to deal with many users with volume permission issues.

**Comment by MatthewVance** [comment]
Thanks for letting me know.
