### ISSUE TITLE
Error while creating caddy container

### ISSUE THREAD

**Issue by Foorack** [abiosoft/caddy-docker#87]
>     root@foosrv1:~# docker run -d \
>     -v $(pwd)/Caddyfile:/etc/Caddyfile \
>     -v $HOME/.caddy:/root/.caddy \
>     -p 80:80 -p 443:443 \
>     abiosoft/caddy

e2e39cee86d09092ed3b37c77cd42120499841483a85b60b5083b7cb94af611e
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:58: mounting \\\"/root/Caddyfile\\\" to rootfs \\\"/var/lib/docker/overlay2/73d4fc495c82b6fe636949d0f0eda98b9628d8f74e5acb11bff7c137081ff960/merged\\\" at \\\"/var/lib/docker/overlay2/73d4fc495c82b6fe636949d0f0eda98b9628d8f74e5acb11bff7c137081ff960/merged/etc/Caddyfile\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

**Comment by gamerlv** [comment]
You received this error because the file `$(pwd)/Caddyfile`  (Caddyfile in the current directory) does not exist, yet you asked docker to mount it.
Create a Caddyfile or remove the mount on line 2. Without the mount [the default Caddyfile](https://github.com/abiosoft/caddy-docker/blob/35e2e2f6e63a17afd18033d14f56af5501702a05/Caddyfile) will be used.

**Comment by abiosoft** [comment]
Yeah, I believe @gamerlv is fairly accurate. If you are able to ascertain that that is indeed not the case, feel free to reopen.
